// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package looprpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssetsClientClient is the client API for AssetsClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetsClientClient interface {
	SwapOut(ctx context.Context, in *SwapOutRequest, opts ...grpc.CallOption) (*SwapOutResponse, error)
}

type assetsClientClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetsClientClient(cc grpc.ClientConnInterface) AssetsClientClient {
	return &assetsClientClient{cc}
}

func (c *assetsClientClient) SwapOut(ctx context.Context, in *SwapOutRequest, opts ...grpc.CallOption) (*SwapOutResponse, error) {
	out := new(SwapOutResponse)
	err := c.cc.Invoke(ctx, "/looprpc.AssetsClient/SwapOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetsClientServer is the server API for AssetsClient service.
// All implementations must embed UnimplementedAssetsClientServer
// for forward compatibility
type AssetsClientServer interface {
	SwapOut(context.Context, *SwapOutRequest) (*SwapOutResponse, error)
	mustEmbedUnimplementedAssetsClientServer()
}

// UnimplementedAssetsClientServer must be embedded to have forward compatible implementations.
type UnimplementedAssetsClientServer struct {
}

func (UnimplementedAssetsClientServer) SwapOut(context.Context, *SwapOutRequest) (*SwapOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapOut not implemented")
}
func (UnimplementedAssetsClientServer) mustEmbedUnimplementedAssetsClientServer() {}

// UnsafeAssetsClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetsClientServer will
// result in compilation errors.
type UnsafeAssetsClientServer interface {
	mustEmbedUnimplementedAssetsClientServer()
}

func RegisterAssetsClientServer(s grpc.ServiceRegistrar, srv AssetsClientServer) {
	s.RegisterService(&AssetsClient_ServiceDesc, srv)
}

func _AssetsClient_SwapOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsClientServer).SwapOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.AssetsClient/SwapOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsClientServer).SwapOut(ctx, req.(*SwapOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetsClient_ServiceDesc is the grpc.ServiceDesc for AssetsClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetsClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "looprpc.AssetsClient",
	HandlerType: (*AssetsClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwapOut",
			Handler:    _AssetsClient_SwapOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clientassets.proto",
}
