// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: secret_key_params.sql

package sqlc

import (
	"context"
)

const getSecretKeyParams = `-- name: GetSecretKeyParams :one
SELECT
  params
FROM
  secret_key_params
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetSecretKeyParams(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSecretKeyParams)
	var params []byte
	err := row.Scan(&params)
	return params, err
}

const insertSecretKeyParams = `-- name: InsertSecretKeyParams :exec
INSERT INTO secret_key_params (
    params
) VALUES (
    $1
)
`

func (q *Queries) InsertSecretKeyParams(ctx context.Context, params []byte) error {
	_, err := q.db.ExecContext(ctx, insertSecretKeyParams, params)
	return err
}
